packages:
  - apps/*
  - packages/*
  - servers/*

ignoredBuiltDependencies:
  - usb

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - electron
  - es5-ext
  - esbuild
  - lzma-native
  - printer
